### ISSUE TITLE
Correct documentation text

### ISSUE THREAD

**Issue by AlexxNB** [AlexxNB/svelte-chota#1]
My english is poor, so the docs text isn't pretty. Necessary to edit the text by somebody who is english native speaker.

**Comment by Beardless-sheik** [comment]
Anybody taken this up? Just started using Svelte recently. I speak decent English. Willing to help

**Comment by AlexxNB** [comment]
Great! Feel free to PR any correction =)

**Comment by kindoflew** [comment]
Is help still needed here? I'm a native English speaker who is new to open-source and would like to contribute!

**Comment by AlexxNB** [comment]
Cool! Will be happy to merge your PRs. =)

**Comment by AlexxNB** [comment]
Thanks @kindoflew - great work: https://github.com/AlexxNB/svelte-chota/pull/19

**Comment by kindoflew** [comment]
No problem! Thanks for all the cool stuff you make! (I'm currently using tinro to build my personal site!)

**Comment by AlexxNB** [comment]
Nice! Tinro's README.md may be improved also 😉

**Comment by kindoflew** [comment]
I'm on it!
