### ISSUE TITLE
Tabs in nav

### ISSUE THREAD

**Issue by constr17** [AlexxNB/svelte-chota#10]
Original chota supports Tab and Button in nav, but in chota-svelte only simple links &lt;a&gt; may be used.

**Comment by AlexxNB** [comment]
Can't figure out what you mean. Nav component is just a`div` with class `nav` (as original is). Can you show problem in the REPL?

**Comment by constr17** [comment]
Example:
https://svelte.dev/repl/b5a3cf34f6054984960806ed00a2e04f
You can see only &lt;a&gt; (you can remove it, and you'll not see tabs). From documentation it is impossible to figure out how to add Tabs to nav, but original chota documentation allows Tabs and Buttons. svelte-chota does not support it, or it is not described it documentation how to use it.

**Comment by AlexxNB** [comment]
`Nav` component may contents only slots named `right`,`left` and `center` (look for the example in docs). To match original semantics  there is no default slot, which you tried to use.

So you should place Tabs in wrapper and put it in of three slots:
```html
<div slot="center"> <!-- or left, or right -->
    <Tabs>
        <Tab>TA</Tab>
          <Tab>Tb</Tab>
     </Tabs>
</div>
```

**Comment by constr17** [comment]
Thank you, but it would be great to add this information to documentation.

**Comment by AlexxNB** [comment]
I don't think so. Example already shows how to use `Nav`. If we will describe all cases how do not use `Nav`(and others) it will be very long documentation. =)
