### ISSUE TITLE
По поводу установки в Sapper

### ISSUE THREAD

**Issue by stilet** [AlexxNB/svelte-chota#11]
Подскажите - есть ли способ установить Ваш пакет в Sapper  без подключения глобального стиля по примеру <link rel="stylesheet" href="https://unpkg.com/chota@latest"> ?
При попытке подключить без вышеприведенной строки, стили не подхватываются.

**Comment by ISNIT0** [comment]
translation of @stilet 

```
Tell me - is there a way to install your package in Sapper without connecting a global style for example?
When trying to connect without the above line, styles are not picked up.
```

**Comment by AlexxNB** [comment]
You must use `chota.min.css` from the `chota` package in any case. `Svelte-chota` is just prepared components based on the chota styles.
