### ISSUE TITLE
Weird errors emerge

### ISSUE THREAD

**Issue by cupcakearmy** [AlexxNB/svelte-chota#13]
Sry for this generic issue, if it's to random just close it xD
Maybe you have an idea what is happening. I have some components that are based of svelte-chota. And they get mounted and unmounted quite often. Sometimes there is this weird thing going on: ` TypeError: Cannot read property 'c' of undefined
    at transition_out` Now the `c` of course is some bundler stuff, but the main issue seems to be the transition_out.

```
// ****/node_modules/svelte-chota/dist/index.js
function transition_out(block, local, detach, callback) {
        if (block && block.o) {
            if (outroing.has(block))
                return;
            outroing.add(block);
            outros.c.push(() => {
                outroing.delete(block);
                if (callback) {
                    if (detach)
                        block.d(1);
                    callback();
                }
            });
            block.o(local);
        }
    }
```

I've looked through your repo and the only transitions are in the modal, which i neither import or use. Also i don't have any transition going on in my project. 

If you have an idea, let me know, other wise just close the issue xD

**Comment by AlexxNB** [comment]
You may try to reproduce this in [REPL](https://svelte.dev/repl). Now I have no idea what happening =)

**Comment by cupcakearmy** [comment]
Ok so it boiled down to having an Input inside of a Field

```svelte
<script>
  // App.svelte
  import { Input, Field } from 'svelte-chota'

  let show = true
</script>

<label>
  <input type="checkbox" bind:checked={show} />
  Show
</label>

{#if show}
  <Field>
    <Input />
  </Field>
{/if}
```

If you toggle it it will crash, however only with parcel, using the official rollup template this does not happen, so it's something inside of the parcel svelte plugin i would guess :) still very strange..

**Comment by AlexxNB** [comment]
Yeah, stranger thing =) Svelte compile should produce equal code both in parcel and rollap. Only the compiler config options may vary.
