### ISSUE TITLE
A11y: A form label must be associated with a control.

### ISSUE THREAD

**Issue by deltalejo** [AlexxNB/svelte-chota#14]
I get the following when building the Svelte app sample (sveltejs/template) using svelte-chota:
```
(!) Plugin svelte: A11y: A form label must be associated with a control.
node_modules/svelte-chota/cmp/Field.svelte
36: <div class:nomessage={!message} use:events {...$$restProps}>
37:   {#if label}
38:     <label>{label}</label>
        ^
39:   {/if}
40:   <p class:grouped class:gapless><slot/></p>
```

**Comment by shu8** [comment]
I also just came across this error, and fixed it temporarily with adding:

```
onwarn: (warning, handler) => {
  if (warning.pluginCode === 'a11y-label-has-associated-control') return;
  handler(warning);
}
```

to my `rollup.config.js`.

---

I tried looking at an actual fix but I'm not sure what the best way to do it is, as the `<slot/>` needs to contain an element with an ID that can be added to the `for="..."` label attribute, but it's not easy to know the ID/generate a unique ID without knowing what's inside the `slot` I think?

**Comment by AlexxNB** [comment]
Maybe, it is a right way to replace `<label>` by `<p>` here?

**Comment by shu8** [comment]
I think a `<label>` would be a bit more useful for accessibility and being able to click on the label text to focus the input inside the `Field`.

We could introduce a `labelFor` prop on `Field` to be the ID of the input that the user is providing inside the `Field` possibly? Maybe like this:

```html
<Field label="Your name" labelFor="name">
  <Input id="name" text />
</Field>
```

**Comment by AlexxNB** [comment]
fixed in https://github.com/AlexxNB/svelte-chota/pull/17

**Comment by schindld** [comment]
There was a regression in [this commit](https://github.com/AlexxNB/svelte-chota/commit/a299f7e808c2830ad3361b5b1bbd9c2efc2bdcdc). It's back to just `<label>{label}</label>` instead of wrapping the label around the slot.
