### ISSUE TITLE
Need to add correct instructions in Readme.md

### ISSUE THREAD

**Issue by prayanks** [AlexxNB/svelte-chota#21]
The current readme.md file doesn't give the full instructions to use svelte-chota properly. 

Edit package.json file and add: 
  "dependencies": {
    "sirv-cli": "^1.0.0",
    **"postcss": "8.2.5"**
  }

In rollup.config.js, in css plugin make the following change: 
svelte({
			compilerOptions: {
				// enable run-time checks when not in production
				dev: !production
			}
			, emitCss: true
		}),
		// we'll extract any component CSS out into
		// a separate file - better for performance
		//css({ output: 'bundle.css' }),

The current README.md is I feel for an older version of Svelte template.

**Comment by prayanks** [comment]
For some reason the css isn't getting picked up. So can't see any chota styling. The components are getting picked up though. 
![image](https://user-images.githubusercontent.com/654009/107128279-80ef5c00-68e2-11eb-987c-6ca11643f603.png)

**Comment by AlexxNB** [comment]
Thanks. Fixed it.
