### ISSUE TITLE
Cannot read property '$$' of undefined

### ISSUE THREAD

**Issue by mathiasrw** [AlexxNB/svelte-chota#22]
Thank you for creating this. 

When using the default init template from https://routify.dev and I include the button example from https://alexxnb.github.io/svelte-chota/usage i get

```
TypeError: Cannot read property '$$' of undefined
    at eval (node_modules/svelte-chota/cmp/utils.js:9)
```

Just wanted to let you know.

**Comment by AlexxNB** [comment]
Thanks. Fixed in v1.8.3
