### ISSUE TITLE
Duplicate slot names using Svelte 3.35

### ISSUE THREAD

**Issue by simonlayfield** [AlexxNB/svelte-chota#25]
Hey!

First of all thanks so much for Svelte Chota!

I thought I'd quickly create something using Svelte Kit this weekend and noticed that there are issues with slots with duplicate names, specifically when I tried to use the Nav component:

```
[plugin:vite-plugin-svelte] Duplicate slot name "right" in <Nav>
```

Looks like this issue was picked up here: https://github.com/sveltejs/svelte/issues/6061

I'm going to see if I can work out what will need to change in order to fix it, but thought I'd add the issue for awareness. Also, I may not have the skill required to get anywhere with fixing it!

**Comment by AlexxNB** [comment]
Yeah, this happening because now we have `<svelte:fragment/>` and can't use multiple `<div slot="blah"></div><div slot="blah"></div>` .
So if you have something like this in your code:
```svelte
<div slot="right">1</div>
<div slot="right">2</div>
```
You should replace it with:
```svelte
<svelte:fragment slot="right">
    <div>1</div>
    <div>2</div>
</svelte:fragment>
```
