### ISSUE TITLE
Modal bind:open

### ISSUE THREAD

**Issue by constr17** [AlexxNB/svelte-chota#9]
In component Modal bind works only with variable open
&lt;Modal bind:open&gt;
It will not open, if you change variable name.

**Comment by AlexxNB** [comment]
May your provide the REPL for this issue?

**Comment by constr17** [comment]
Unfortunately I don't have experience to configure svelte-project in REPL. Can you show me any example (better with svelte-chota)?

**Comment by AlexxNB** [comment]
Shure: https://svelte.dev/repl/3f30b08107444a788c26cab959adfedf?version=3.22.2

**Comment by constr17** [comment]
It's "Failed to fetch", but I see problem.
Example in documentation:
`
<Button on:click={e => open=true}>Show modal</Button>
<Modal bind:open>
`
Example in REPL:
`
<Button on:click={e => showModal=true}>Show modal</Button>
<Modal bind:open={showModal}>
`
In first case everything works only if variable colled 'open'. So, it is better to correct documentation.

**Comment by AlexxNB** [comment]
`bind:open` is Svelte's shorthand for `bind:open={open}`. So the documentation is correct. When you need to bind Modal's `open` property to any variable - you should use full form - `bind:open={variable}`.

> It's "Failed to fetch", but I see problem.
Try to reload. Works great for me.
